apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-processors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: ota-processors
    spec:
      containers:
      - name: ota-processors
        image: 795914468022.dkr.ecr.us-east-1.amazonaws.com/online-travel-agency:proc-latest
        ports:
        - containerPort: 8090