apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-suppliers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supplier
  template:
    metadata:
      labels:
        app: ota-supplier
    spec:
      containers:
      - name: ota-suppliers
        image: 795914468022.dkr.ecr.us-east-1.amazonaws.com/online-travel-agency:supp-latest
        ports:
        - containerPort: 8080