apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-suppliers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ota-supplier
  template:
    metadata:
      labels:
        app: ota-supplier
    spec:
      containers:
      - name: ota-supp-container
        image: 795914468022.dkr.ecr.us-east-1.amazonaws.com/online-travel-agency:supp-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080