apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-adapters
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ota-adapter
  template:
    metadata:
      labels:
        app: ota-adapter
    spec:
      containers:
      - name: ota-adap-container
        image: 795914468022.dkr.ecr.us-east-1.amazonaws.com/online-travel-agency:adap-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000